# Generated by Django 4.1.7 on 2023-02-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carerra', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto_emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=254)),
                ('parentesco', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('folio', models.IntegerField(primary_key=True, serialize=False)),
                ('codigoQR', models.ImageField(upload_to='codigos_qr/')),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('contador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('numero_control', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('correo', models.EmailField(max_length=254)),
                ('fotografia', models.ImageField(upload_to='fotografias_otros/')),
                ('Contacto_emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.contacto_emergencia')),
                ('credencial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.credencial')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('numero_control', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('correo', models.EmailField(max_length=254)),
                ('fotografia', models.ImageField(upload_to='fotografias_docentes/')),
                ('telefono', models.CharField(max_length=13)),
                ('Contacto_emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.contacto_emergencia')),
                ('credencial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.credencial')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('correo', models.EmailField(default='<django.db.models.fields.IntegerField>@uptapachula.edu.mx', max_length=254)),
                ('cuatrimestre', models.IntegerField(choices=[(1, 'primer cuatrimestre'), (2, 'segundo cuatrimestre'), (3, 'tercer cuatrimestre'), (4, 'cuarto cuatrimestre'), (5, 'quinto cuatrimestre'), (6, 'sexto cuatrimestre'), (7, 'septimo cuatrimestre'), (8, 'octavo cuatrimestre'), (9, 'noveno cuatrimestre'), (10, 'decimo cuatrimestre')])),
                ('fotografia', models.ImageField(upload_to='fotografias_alumnos/')),
                ('telefono', models.CharField(max_length=13)),
                ('Contacto_emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.contacto_emergencia')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.carrera')),
                ('credencial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.credencial')),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('numero_control', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=15)),
                ('apellido_materno', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('correo', models.EmailField(max_length=254)),
                ('fotografia', models.ImageField(upload_to='fotografias_administrativos/')),
                ('telefono', models.CharField(max_length=13)),
                ('cargo', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('Contacto_emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.contacto_emergencia')),
                ('credencial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scd.credencial')),
            ],
        ),
    ]
