# Generated by Django 4.1.7 on 2023-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0004_alter_alumno_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativo',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='fotografias_administrativos/'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='fotografias_docentes/'),
        ),
        migrations.AlterField(
            model_name='otros',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='fotografias_otros/'),
        ),
    ]
