# Generated by Django 4.1.7 on 2023-07-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0005_alter_administrativo_fotografia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='Contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='credencial',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='Contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='credencial',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='Contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='credencial',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='Contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='credencial',
        ),
        migrations.DeleteModel(
            name='Contacto_emergencia',
        ),
        migrations.DeleteModel(
            name='Credencial',
        ),
    ]
