# Generated by Django 4.1.7 on 2023-07-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0006_remove_administrativo_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='apellido_materno_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='apellido_paterno_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='nombre_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='parentescto_contactoe',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Otro', 'Otro')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='password',
            field=models.CharField(default='nimda', max_length=128),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='telefono_contactoe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_materno_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_paterno_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='parentescto_contactoe',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Otro', 'Otro')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(default='<django.db.models.fields.IntegerField>', max_length=128),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_contactoe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='docente',
            name='apellido_materno_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='docente',
            name='apellido_paterno_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='docente',
            name='nombre_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='docente',
            name='parentescto_contactoe',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Otro', 'Otro')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='docente',
            name='password',
            field=models.CharField(default='<django.db.models.fields.IntegerField>', max_length=128),
        ),
        migrations.AddField(
            model_name='docente',
            name='telefono_contactoe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='otros',
            name='apellido_materno_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='otros',
            name='apellido_paterno_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='otros',
            name='nombre_contactoe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='otros',
            name='parentescto_contactoe',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Otro', 'Otro')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='otros',
            name='password',
            field=models.CharField(default='<django.db.models.fields.IntegerField>', max_length=128),
        ),
        migrations.AddField(
            model_name='otros',
            name='telefono_contactoe',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(choices=[('Ingenieria de software', 'Ingenieria de software'), ('Ingenieria mecatronica', 'Ingenieria mecatronica'), ('Ingenieria en animacion y efectos visuales', 'Ingenieria en animacion y efectos visuales')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carreras',
            name='nombre_carrera',
            field=models.CharField(choices=[('Ingenieria de software', 'Ingenieria de software'), ('Ingenieria mecatronica', 'Ingenieria mecatronica'), ('Ingenieria en animacion y efectos visuales', 'Ingenieria en animacion y efectos visuales')], max_length=50),
        ),
    ]
