# Generated by Django 4.1.7 on 2023-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0007_administrativo_apellido_materno_contactoe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='credencial_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='credencial_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='credencial_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otros',
            name='credencial_activa',
            field=models.BooleanField(default=True),
        ),
    ]
