# Generated by Django 4.1.7 on 2023-07-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0012_rename_correo_administrativo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
