# Generated by Django 4.1.7 on 2023-07-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0013_alumno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
