# Generated by Django 4.1.7 on 2023-07-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('scd', '0014_alter_alumno_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='administrativo_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='administrativo_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='administrativo',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='alumno_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='alumno_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='docente_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='docente',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='docente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='docente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='docente_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='docente',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='otros',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='otros_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='otros',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='otros',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='otros',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='otros_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='otros',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='otros',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
