# Generated by Django 4.1.7 on 2023-07-10 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scd', '0015_administrativo_groups_administrativo_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='username',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='password',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='username',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='username',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='password',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='username',
        ),
        migrations.AddField(
            model_name='administrativo',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otros',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
