# Generated by Django 4.1.7 on 2023-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0018_alter_administrativo_user_alter_docente_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='user',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='otros',
            name='user',
        ),
        migrations.AddField(
            model_name='alumno',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
