# Generated by Django 4.1.7 on 2023-07-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0019_remove_administrativo_user_remove_alumno_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
