# Generated by Django 4.1.7 on 2023-07-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0020_remove_alumno_is_active_remove_alumno_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
