# Generated by Django 4.1.7 on 2023-07-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0021_alumno_is_active_alumno_is_staff_alumno_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='password',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
