# Generated by Django 4.1.7 on 2023-07-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0022_remove_alumno_is_active_remove_alumno_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='password',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
