# Generated by Django 4.1.7 on 2023-07-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scd', '0023_alumno_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativo',
            name='apellido_materno_contactoe',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='apellido_paterno_contactoe',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='area',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='credencial_activa',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='fotografia',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='nombre_contactoe',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='parentescto_contactoe',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='telefono_contactoe',
        ),
        migrations.RemoveField(
            model_name='administrativo',
            name='tipo_sangre',
        ),
        migrations.AddField(
            model_name='administrativo',
            name='password',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nss',
            field=models.CharField(default=' ', max_length=25),
        ),
        migrations.AddField(
            model_name='docente',
            name='nss',
            field=models.CharField(default=' ', max_length=25),
        ),
        migrations.AddField(
            model_name='docente',
            name='password',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AddField(
            model_name='otros',
            name='area',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='otros',
            name='cargo',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='otros',
            name='nss',
            field=models.CharField(default=' ', max_length=25),
        ),
        migrations.AddField(
            model_name='otros',
            name='password',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
